PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization:

{
    "name": "updated Go Conference",
    "description": "updated description",
    "location": "updated location",
    "date_time": "2025-09-15T09:00:00Z"
}
